CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN (
      # Write your MySQL query statement below.
      SELECT DISTINCT SALARY FROM(SELECT SALARY,DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RNK FROM EMPLOYEE) AS SUB WHERE RNK=N
  );
END